apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
data:
  SECRET_KEY: "your-secret-key"
  DEBUG: "true"

  # Database settings
  DBNAME: "postgres"
  DBUSER: "postgres"
  DBPASSWORD: "postgres"
  DBHOST: "localhost"
  DBPORT: "5432"

  # Redis settings
  REDIS_USERNAME: ""
  REDIS_PASSWORD: ""
  REDIS_HOST: "localhost"
  REDIS_PORT: "6379"

  # Email settings
  EMAIL_HOST: "your_email_host"
  EMAIL_PORT: "your_email_port"
  EMAIL_HOST_USER: "your_email_user"
  EMAIL_HOST_PASSWORD: "your_email_password"

  # Allowed hosts & CORS
  ALLOWED_HOSTS: "localhost,127.0.0.1"
  CORS_ORIGINS: "localhost,127.0.0.1,*"
